<a href="https://colab.research.google.com/github/TFremon/MLBTS/blob/main/MLBTS_PWARv2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
#@title
#Imports
import math
import numpy as np
from plotly.subplots import make_subplots
from scipy.optimize import minimize
import plotly.io as pio
pio.templates.default='plotly_dark'

In [18]:
#@title
# Data get
!wget https://raw.githubusercontent.com/TFremon/MLBTS/main/Book1.csv


--2022-08-01 02:30:40--  https://raw.githubusercontent.com/TFremon/MLBTS/main/Book1.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 318 [text/plain]
Saving to: ‘Book1.csv.1’

Book1.csv.1         100%[===================>]     318  --.-KB/s    in 0s      

2022-08-01 02:30:40 (24.0 MB/s) - ‘Book1.csv.1’ saved [318/318]



In [19]:
#@title
# Get data, create array
data = np.loadtxt('Book1.csv', delimiter=',')


In [20]:
#@title
ip = data[:,0]
fip = data[:,1]
war = data[:,2]


ip


array([110.  , 115.67,  99.  , 110.2 , 100.  , 100.33, 106.33, 239.  ,
       230.67, 220.33, 207.  , 210.67, 227.67, 200.33, 194.33, 191.67,
       199.  , 206.1 , 215.  ])

In [21]:
def sse_war(v):
  fact = v
  war_er = 0
  for i in range(len(ip)):
    war_er = war_er + ((ip[i] / fip[i]) * fact - war[i])**2
  return war_er



In [22]:
#@title
factor = minimize(sse_war,[1]).x
factor

array([0.06718615])

In [24]:
#@title
#error prediction using parameters
def war_predict(vals):
  ip_i, fip_i = vals

  return (ip_i / fip_i) * factor

war_predict([180, 1.1])



array([10.99409692])